### PR TITLE
Fixes #28: Form validation

### LINKED ISSUE #28: Form validation
This is a good first issue to validate the input form before sending an API call.

**To Reproduce**
1. Click the extension
2. Enter fields but don't choose any list
3. Click 'Add to Trello' button
4. Error is shown and refreshing it means all info is gone

**Expected behavior**
The screen should tell users to choose a list before sending the POST request, preserving the data.

**Further enhancement**
The error div should have a link to hide the error div and display the original div again, in case the error is not related to form invalidation.

### PR DESCRIPTION
**Pull request by slaterslater**
* alert box displays if Trello list not chosen
* close button added to alert box
* choosing a Trello list will close alert box

### CODE REVIEW

**Comment by HarshdipD** [comment]
@slaterslater  thank you for such a quick solution! This works perfectly. I'll merge this PR now. 
Feel free to take any other issue if you're interested and star this repo!

**Comment by HarshdipD** [comment]
@slaterslater  sorry, I think I need one more commit from you. I merged a previous PR (#21 ) and this might cause merge conflicts, could you please solve that from your end and send a new push.

**Comment by slaterslater** [comment]
@HarshdipD is there still an issue? Can you help me understand what is needed from me?

**Comment by HarshdipD** [comment]
@slaterslater  no, I fixed that myself! Your PR along with other recent ones are included in v1.2 and submitted to the chrome web store, and you will see it in action by 1-2 days! Thanks again!

**Pull request merged**
